version: '3'
services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - ./.config/prod/postgres.env
    networks:
      - backend

  redis:
    image: 'redis:latest'
    networks:
      - backend

  client:
    image: michalmon/tch-z2:client
    networks:
      backend:
        aliases:
          - client

  api:
    image: michalmon/tch-z2:api
    env_file:
      - ./.config/prod/api.env
    networks:
      backend:
        aliases:
          - api

  worker:
    image: michalmon/tch-z2:worker
    env_file:
      - ./.config/prod/worker.env
    networks:
      - backend

  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: michalmon/tch-z2:nginx
    ports:
      - '3050:80'
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
