apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 2 
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: michalmon/pfswcho-worker:main
        ports:
        - containerPort: 80
