apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
  replicas: 2 
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: michalmon/tch-z2:client
        ports:
        - containerPort: 80