apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: client
  replicas: 2 
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: michalmon/pfswcho-client:main
        ports:
        - containerPort: 80
