apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2 
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: michalmon/tch-z2:api
        ports:
        - containerPort: 80
