# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: "pfswcho-projekt"
  IMAGE_TAG: "api"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./src/api/Dockerfile
            image: michalmon/pfswcho:api
          - dockerfile: ./src/client/Dockerfile
            image: michalmon/pfswcho:client
          - dockerfile: ./src/nginx/Dockerfile
            image: michalmon/pfswcho:nginx
          - dockerfile: ./src/worker/Dockerfile
            image: michalmon/pfswcho:worker
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #Konfiguracja Buildx i Docker
      - name: Buildx & Docker setup
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      #Instalacja QEMU
      - name: Docker QEMU Setup
        uses: docker/setup-qemu-action@v1.2.0

      #Logowanie do Dockerhub
      - name: Dockerhub Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      #Wyciągnięcie tagów i labeli z metadanych
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          
      #Zbudowanie i wypchniecie obrazu do Dockerhub
      - name: Build & push Dockerhub
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.dockerfile }}
          push: true

